{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "\n",
    "import napari\n",
    "import os\n",
    "import glob\n",
    "from pathlib import Path\n",
    "from tifffile import imread\n",
    "import numpy as np\n",
    "import csv\n",
    "import pandas as pd\n",
    "from qtpy.QtWidgets import QComboBox, QPushButton, QSlider\n",
    "%gui qt"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [],
   "source": [
    "def MidSlices(Image, start_project_mid, end_project_mid, axis = 1):\n",
    "    \n",
    "    \n",
    "    SmallImage = Image.take(indices = range(Image.shape[axis]//2 - start_project_mid, Image.shape[axis]//2 + end_project_mid), axis = axis)\n",
    "    \n",
    "    MaxProject = np.amax(SmallImage, axis = axis)\n",
    "        \n",
    "    return MaxProject\n",
    "\n",
    "class EventViewer(object):\n",
    "    \n",
    "    def __init__(self, viewer, imagename, Name, csv_dir, save = False, newimage = True, start_project_mid = 4, end_project_mid = 1):\n",
    "     \n",
    "          self.save = save\n",
    "          self.newimage = newimage\n",
    "          self.viewer = viewer\n",
    "          self.start_project_mid = start_project_mid\n",
    "          self.end_project_mid = end_project_mid  \n",
    "          print('reading image')      \n",
    "          self.imagename = imagename  \n",
    "          self.image = imread(imagename)\n",
    "          print('image read')\n",
    "          self.Name = Name\n",
    "          self.ndim = len(self.image.shape)  \n",
    "          self.csv_dir = csv_dir\n",
    "          if self.ndim == 4:\n",
    "              self.image = MidSlices(self.image, self.start_project_mid, self.end_project_mid)\n",
    "          \n",
    "          self.click()\n",
    "    def click(self):\n",
    "\n",
    "        \n",
    "                ClassBackground = 'Normal'\n",
    "                ClassDivision = 'Division'\n",
    "                \n",
    "                if self.save == True:\n",
    " \n",
    "                        ClassBackgrounddata = self.viewer.layers[ClassBackground].data\n",
    "                        bgdf = pd.DataFrame(ClassBackgrounddata, index = None, columns = ['T', 'Y', 'X'])\n",
    "                        bgdf.to_csv(self.csv_dir + '/' + 'ONEAT' + ClassBackground + self.Name +  '.csv', index = False, mode = 'w')\n",
    "\n",
    "                        ClassDivisiondata = self.viewer.layers[ClassDivision].data\n",
    "                        divdf = pd.DataFrame(ClassDivisiondata, index = None, columns = ['T', 'Y', 'X'])\n",
    "                        divdf.to_csv(self.csv_dir + '/' +'ONEAT' + ClassDivision + self.Name +  '.csv', index = False, mode = 'w')\n",
    "\n",
    "                       \n",
    "        \n",
    "                if self.newimage == True:\n",
    "                     for layer in list(self.viewer.layers):\n",
    "\n",
    "                            self.viewer.layers.remove(layer) \n",
    "                    \n",
    "                if self.save == False:\n",
    "                        self.viewer.add_image(self.image, name = self.Name)\n",
    "\n",
    "\n",
    "                        # add the first points layer for ClassBackground T point\n",
    "                        self.viewer.add_points(name= ClassBackground, face_color='red', ndim = 3)\n",
    "\n",
    "                        # add the second points layer for ClassDivision T point\n",
    "                        self.viewer.add_points(name= ClassDivision, face_color='blue', ndim = 3)\n",
    "\n",
    "                      \n",
    "                        # programatically enter add mode for both Points layers to enable editing\n",
    "\n",
    "                        self.viewer.layers[ClassBackground].mode = 'add'\n",
    "                        self.viewer.layers[ClassDivision].mode = 'add'\n",
    "                       "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "C:\\Users\\rando\\anaconda3\\envs\\naparienv\\lib\\site-packages\\napari_tools_menu\\__init__.py:165: FutureWarning: Public access to Window.qt_viewer is deprecated and will be removed in\n",
      "v0.5.0. It is considered an \"implementation detail\" of the napari\n",
      "application, not part of the napari viewer model. If your use case\n",
      "requires access to qt_viewer, please open an issue to discuss.\n",
      "  self.tools_menu = ToolsMenu(self, self.qt_viewer.viewer)\n"
     ]
    },
    {
     "data": {
      "text/plain": [
       "<PyQt5.QtCore.QMetaObject.Connection at 0x19eb8bfa3c0>"
      ]
     },
     "execution_count": 3,
     "metadata": {},
     "output_type": "execute_result"
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "reading image\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "<tifffile.TiffPage 0 @8> imagej_metadata failed with ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "image read\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "C:\\Users\\rando\\AppData\\Roaming\\Python\\Python39\\site-packages\\napari\\_vispy\\layers\\image.py:242: UserWarning: data shape (53, 2292, 2292) exceeds GL_MAX_TEXTURE_SIZE 2048 in at least one axis and will be downsampled. Rendering is currently in 3D mode.\n",
      "  warnings.warn(\n",
      "WARNING:tifffile.tifffile:<tifffile.TiffPage 0 @8> imagej_metadata failed with ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()\n",
      "C:\\Users\\rando\\AppData\\Roaming\\Python\\Python39\\site-packages\\napari\\_vispy\\layers\\image.py:242: UserWarning: data shape (22, 2292, 2292) exceeds GL_MAX_TEXTURE_SIZE 2048 in at least one axis and will be downsampled. Rendering is currently in 3D mode.\n",
      "  warnings.warn(\n",
      "C:\\Users\\rando\\AppData\\Roaming\\Python\\Python39\\site-packages\\napari\\_vispy\\layers\\image.py:242: UserWarning: data shape (22, 2292, 2292) exceeds GL_MAX_TEXTURE_SIZE 2048 in at least one axis and will be downsampled. Rendering is currently in 3D mode.\n",
      "  warnings.warn(\n",
      "C:\\Users\\rando\\AppData\\Roaming\\Python\\Python39\\site-packages\\napari\\_vispy\\layers\\image.py:242: UserWarning: data shape (22, 2292, 2292) exceeds GL_MAX_TEXTURE_SIZE 2048 in at least one axis and will be downsampled. Rendering is currently in 3D mode.\n",
      "  warnings.warn(\n",
      "C:\\Users\\rando\\AppData\\Roaming\\Python\\Python39\\site-packages\\napari\\_vispy\\layers\\image.py:242: UserWarning: data shape (22, 2292, 2292) exceeds GL_MAX_TEXTURE_SIZE 2048 in at least one axis and will be downsampled. Rendering is currently in 3D mode.\n",
      "  warnings.warn(\n",
      "C:\\Users\\rando\\AppData\\Roaming\\Python\\Python39\\site-packages\\napari\\_vispy\\layers\\image.py:242: UserWarning: data shape (22, 2292, 2292) exceeds GL_MAX_TEXTURE_SIZE 2048 in at least one axis and will be downsampled. Rendering is currently in 3D mode.\n",
      "  warnings.warn(\n",
      "C:\\Users\\rando\\AppData\\Roaming\\Python\\Python39\\site-packages\\napari\\_vispy\\layers\\image.py:242: UserWarning: data shape (22, 2292, 2292) exceeds GL_MAX_TEXTURE_SIZE 2048 in at least one axis and will be downsampled. Rendering is currently in 3D mode.\n",
      "  warnings.warn(\n",
      "C:\\Users\\rando\\AppData\\Roaming\\Python\\Python39\\site-packages\\napari\\_vispy\\layers\\image.py:242: UserWarning: data shape (22, 2292, 2292) exceeds GL_MAX_TEXTURE_SIZE 2048 in at least one axis and will be downsampled. Rendering is currently in 3D mode.\n",
      "  warnings.warn(\n",
      "C:\\Users\\rando\\AppData\\Roaming\\Python\\Python39\\site-packages\\napari\\_vispy\\layers\\image.py:242: UserWarning: data shape (22, 2292, 2292) exceeds GL_MAX_TEXTURE_SIZE 2048 in at least one axis and will be downsampled. Rendering is currently in 3D mode.\n",
      "  warnings.warn(\n",
      "C:\\Users\\rando\\AppData\\Roaming\\Python\\Python39\\site-packages\\napari\\_vispy\\layers\\image.py:242: UserWarning: data shape (22, 2292, 2292) exceeds GL_MAX_TEXTURE_SIZE 2048 in at least one axis and will be downsampled. Rendering is currently in 3D mode.\n",
      "  warnings.warn(\n",
      "C:\\Users\\rando\\AppData\\Roaming\\Python\\Python39\\site-packages\\napari\\_vispy\\layers\\image.py:242: UserWarning: data shape (22, 2292, 2292) exceeds GL_MAX_TEXTURE_SIZE 2048 in at least one axis and will be downsampled. Rendering is currently in 3D mode.\n",
      "  warnings.warn(\n",
      "C:\\Users\\rando\\AppData\\Roaming\\Python\\Python39\\site-packages\\napari\\_vispy\\layers\\image.py:242: UserWarning: data shape (22, 2292, 2292) exceeds GL_MAX_TEXTURE_SIZE 2048 in at least one axis and will be downsampled. Rendering is currently in 3D mode.\n",
      "  warnings.warn(\n",
      "C:\\Users\\rando\\AppData\\Roaming\\Python\\Python39\\site-packages\\napari\\_vispy\\layers\\image.py:242: UserWarning: data shape (22, 2292, 2292) exceeds GL_MAX_TEXTURE_SIZE 2048 in at least one axis and will be downsampled. Rendering is currently in 3D mode.\n",
      "  warnings.warn(\n",
      "C:\\Users\\rando\\AppData\\Roaming\\Python\\Python39\\site-packages\\napari\\_vispy\\layers\\image.py:242: UserWarning: data shape (182, 2072, 4030) exceeds GL_MAX_TEXTURE_SIZE 2048 in at least one axis and will be downsampled. Rendering is currently in 3D mode.\n",
      "  warnings.warn(\n",
      "WARNING: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\rando\\anaconda3\\envs\\naparienv\\lib\\runpy.py\", line 197, in _run_module_as_main\n",
      "    return _run_code(code, main_globals, None,\n",
      "  File \"C:\\Users\\rando\\anaconda3\\envs\\naparienv\\lib\\runpy.py\", line 87, in _run_code\n",
      "    exec(code, run_globals)\n",
      "  File \"C:\\Users\\rando\\anaconda3\\envs\\naparienv\\lib\\site-packages\\ipykernel_launcher.py\", line 16, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"C:\\Users\\rando\\anaconda3\\envs\\naparienv\\lib\\site-packages\\traitlets\\config\\application.py\", line 846, in launch_instance\n",
      "    app.start()\n",
      "  File \"C:\\Users\\rando\\anaconda3\\envs\\naparienv\\lib\\site-packages\\ipykernel\\kernelapp.py\", line 677, in start\n",
      "    self.io_loop.start()\n",
      "  File \"C:\\Users\\rando\\anaconda3\\envs\\naparienv\\lib\\site-packages\\tornado\\platform\\asyncio.py\", line 199, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"C:\\Users\\rando\\anaconda3\\envs\\naparienv\\lib\\asyncio\\base_events.py\", line 596, in run_forever\n",
      "    self._run_once()\n",
      "  File \"C:\\Users\\rando\\anaconda3\\envs\\naparienv\\lib\\asyncio\\base_events.py\", line 1890, in _run_once\n",
      "    handle._run()\n",
      "  File \"C:\\Users\\rando\\anaconda3\\envs\\naparienv\\lib\\asyncio\\events.py\", line 80, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Users\\rando\\anaconda3\\envs\\naparienv\\lib\\site-packages\\tornado\\ioloop.py\", line 741, in _run_callback\n",
      "    ret = callback()\n",
      "  File \"C:\\Users\\rando\\anaconda3\\envs\\naparienv\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 402, in advance_eventloop\n",
      "    eventloop(self)\n",
      "  File \"C:\\Users\\rando\\anaconda3\\envs\\naparienv\\lib\\site-packages\\ipykernel\\eventloops.py\", line 137, in loop_qt5\n",
      "    return loop_qt4(kernel)\n",
      "  File \"C:\\Users\\rando\\anaconda3\\envs\\naparienv\\lib\\site-packages\\ipykernel\\eventloops.py\", line 121, in loop_qt4\n",
      "    _loop_qt(kernel.app)\n",
      "  File \"C:\\Users\\rando\\anaconda3\\envs\\naparienv\\lib\\site-packages\\ipykernel\\eventloops.py\", line 105, in _loop_qt\n",
      "    app.exec_()\n",
      "  File \"C:\\Users\\rando\\anaconda3\\envs\\naparienv\\lib\\site-packages\\vispy\\app\\backends\\_qt.py\", line 567, in event\n",
      "    out = super(QtBaseCanvasBackend, self).event(ev)\n",
      "  File \"C:\\Users\\rando\\anaconda3\\envs\\naparienv\\lib\\site-packages\\vispy\\app\\backends\\_qt.py\", line 532, in mouseMoveEvent\n",
      "    self._vispy_mouse_move(\n",
      "  File \"C:\\Users\\rando\\anaconda3\\envs\\naparienv\\lib\\site-packages\\vispy\\app\\base.py\", line 216, in _vispy_mouse_move\n",
      "    ev = self._vispy_canvas.events.mouse_move(**kwargs)\n",
      "  File \"C:\\Users\\rando\\anaconda3\\envs\\naparienv\\lib\\site-packages\\vispy\\util\\event.py\", line 453, in __call__\n",
      "    self._invoke_callback(cb, event)\n",
      "  File \"C:\\Users\\rando\\anaconda3\\envs\\naparienv\\lib\\site-packages\\vispy\\util\\event.py\", line 469, in _invoke_callback\n",
      "    cb(event)\n",
      "  File \"C:\\Users\\rando\\AppData\\Roaming\\Python\\Python39\\site-packages\\napari\\_vispy\\canvas.py\", line 98, in _process_mouse_event\n",
      "    super()._process_mouse_event(event)\n",
      "  File \"C:\\Users\\rando\\anaconda3\\envs\\naparienv\\lib\\site-packages\\vispy\\scene\\canvas.py\", line 369, in _process_mouse_event\n",
      "    getattr(picked.events, event.type)(scene_event)\n",
      "  File \"C:\\Users\\rando\\anaconda3\\envs\\naparienv\\lib\\site-packages\\vispy\\util\\event.py\", line 453, in __call__\n",
      "    self._invoke_callback(cb, event)\n",
      "  File \"C:\\Users\\rando\\anaconda3\\envs\\naparienv\\lib\\site-packages\\vispy\\util\\event.py\", line 471, in _invoke_callback\n",
      "    _handle_exception(self.ignore_callback_errors,\n",
      "  << caught exception here: >>\n",
      "  File \"C:\\Users\\rando\\anaconda3\\envs\\naparienv\\lib\\site-packages\\vispy\\util\\event.py\", line 469, in _invoke_callback\n",
      "    cb(event)\n",
      "  File \"C:\\Users\\rando\\anaconda3\\envs\\naparienv\\lib\\site-packages\\vispy\\scene\\cameras\\perspective.py\", line 227, in viewbox_mouse_event\n",
      "    self._update_rotation(event)\n",
      "  File \"C:\\Users\\rando\\anaconda3\\envs\\naparienv\\lib\\site-packages\\vispy\\scene\\cameras\\arcball.py\", line 65, in _update_rotation\n",
      "    Quaternion(*_arcball(self._event_value, wh)) *\n",
      "  File \"C:\\Users\\rando\\anaconda3\\envs\\naparienv\\lib\\site-packages\\vispy\\scene\\cameras\\arcball.py\", line 101, in _arcball\n",
      "    x, y = xy\n",
      "ValueError: too many values to unpack (expected 2)\n",
      "WARNING:vispy:Traceback (most recent call last):\n",
      "  File \"C:\\Users\\rando\\anaconda3\\envs\\naparienv\\lib\\runpy.py\", line 197, in _run_module_as_main\n",
      "    return _run_code(code, main_globals, None,\n",
      "  File \"C:\\Users\\rando\\anaconda3\\envs\\naparienv\\lib\\runpy.py\", line 87, in _run_code\n",
      "    exec(code, run_globals)\n",
      "  File \"C:\\Users\\rando\\anaconda3\\envs\\naparienv\\lib\\site-packages\\ipykernel_launcher.py\", line 16, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"C:\\Users\\rando\\anaconda3\\envs\\naparienv\\lib\\site-packages\\traitlets\\config\\application.py\", line 846, in launch_instance\n",
      "    app.start()\n",
      "  File \"C:\\Users\\rando\\anaconda3\\envs\\naparienv\\lib\\site-packages\\ipykernel\\kernelapp.py\", line 677, in start\n",
      "    self.io_loop.start()\n",
      "  File \"C:\\Users\\rando\\anaconda3\\envs\\naparienv\\lib\\site-packages\\tornado\\platform\\asyncio.py\", line 199, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"C:\\Users\\rando\\anaconda3\\envs\\naparienv\\lib\\asyncio\\base_events.py\", line 596, in run_forever\n",
      "    self._run_once()\n",
      "  File \"C:\\Users\\rando\\anaconda3\\envs\\naparienv\\lib\\asyncio\\base_events.py\", line 1890, in _run_once\n",
      "    handle._run()\n",
      "  File \"C:\\Users\\rando\\anaconda3\\envs\\naparienv\\lib\\asyncio\\events.py\", line 80, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Users\\rando\\anaconda3\\envs\\naparienv\\lib\\site-packages\\tornado\\ioloop.py\", line 741, in _run_callback\n",
      "    ret = callback()\n",
      "  File \"C:\\Users\\rando\\anaconda3\\envs\\naparienv\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 402, in advance_eventloop\n",
      "    eventloop(self)\n",
      "  File \"C:\\Users\\rando\\anaconda3\\envs\\naparienv\\lib\\site-packages\\ipykernel\\eventloops.py\", line 137, in loop_qt5\n",
      "    return loop_qt4(kernel)\n",
      "  File \"C:\\Users\\rando\\anaconda3\\envs\\naparienv\\lib\\site-packages\\ipykernel\\eventloops.py\", line 121, in loop_qt4\n",
      "    _loop_qt(kernel.app)\n",
      "  File \"C:\\Users\\rando\\anaconda3\\envs\\naparienv\\lib\\site-packages\\ipykernel\\eventloops.py\", line 105, in _loop_qt\n",
      "    app.exec_()\n",
      "  File \"C:\\Users\\rando\\anaconda3\\envs\\naparienv\\lib\\site-packages\\vispy\\app\\backends\\_qt.py\", line 567, in event\n",
      "    out = super(QtBaseCanvasBackend, self).event(ev)\n",
      "  File \"C:\\Users\\rando\\anaconda3\\envs\\naparienv\\lib\\site-packages\\vispy\\app\\backends\\_qt.py\", line 532, in mouseMoveEvent\n",
      "    self._vispy_mouse_move(\n",
      "  File \"C:\\Users\\rando\\anaconda3\\envs\\naparienv\\lib\\site-packages\\vispy\\app\\base.py\", line 216, in _vispy_mouse_move\n",
      "    ev = self._vispy_canvas.events.mouse_move(**kwargs)\n",
      "  File \"C:\\Users\\rando\\anaconda3\\envs\\naparienv\\lib\\site-packages\\vispy\\util\\event.py\", line 453, in __call__\n",
      "    self._invoke_callback(cb, event)\n",
      "  File \"C:\\Users\\rando\\anaconda3\\envs\\naparienv\\lib\\site-packages\\vispy\\util\\event.py\", line 469, in _invoke_callback\n",
      "    cb(event)\n",
      "  File \"C:\\Users\\rando\\AppData\\Roaming\\Python\\Python39\\site-packages\\napari\\_vispy\\canvas.py\", line 98, in _process_mouse_event\n",
      "    super()._process_mouse_event(event)\n",
      "  File \"C:\\Users\\rando\\anaconda3\\envs\\naparienv\\lib\\site-packages\\vispy\\scene\\canvas.py\", line 369, in _process_mouse_event\n",
      "    getattr(picked.events, event.type)(scene_event)\n",
      "  File \"C:\\Users\\rando\\anaconda3\\envs\\naparienv\\lib\\site-packages\\vispy\\util\\event.py\", line 453, in __call__\n",
      "    self._invoke_callback(cb, event)\n",
      "  File \"C:\\Users\\rando\\anaconda3\\envs\\naparienv\\lib\\site-packages\\vispy\\util\\event.py\", line 471, in _invoke_callback\n",
      "    _handle_exception(self.ignore_callback_errors,\n",
      "  << caught exception here: >>\n",
      "  File \"C:\\Users\\rando\\anaconda3\\envs\\naparienv\\lib\\site-packages\\vispy\\util\\event.py\", line 469, in _invoke_callback\n",
      "    cb(event)\n",
      "  File \"C:\\Users\\rando\\anaconda3\\envs\\naparienv\\lib\\site-packages\\vispy\\scene\\cameras\\perspective.py\", line 227, in viewbox_mouse_event\n",
      "    self._update_rotation(event)\n",
      "  File \"C:\\Users\\rando\\anaconda3\\envs\\naparienv\\lib\\site-packages\\vispy\\scene\\cameras\\arcball.py\", line 65, in _update_rotation\n",
      "    Quaternion(*_arcball(self._event_value, wh)) *\n",
      "  File \"C:\\Users\\rando\\anaconda3\\envs\\naparienv\\lib\\site-packages\\vispy\\scene\\cameras\\arcball.py\", line 101, in _arcball\n",
      "    x, y = xy\n",
      "ValueError: too many values to unpack (expected 2)\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR: Invoking <bound method Base3DRotationCamera.viewbox_mouse_event of <ArcballCamera at 0x19eb8eec670>> for SceneMouseEvent\n",
      "ERROR:vispy:Invoking <bound method Base3DRotationCamera.viewbox_mouse_event of <ArcballCamera at 0x19eb8eec670>> for SceneMouseEvent\n",
      "WARNING: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\rando\\anaconda3\\envs\\naparienv\\lib\\runpy.py\", line 197, in _run_module_as_main\n",
      "    return _run_code(code, main_globals, None,\n",
      "  File \"C:\\Users\\rando\\anaconda3\\envs\\naparienv\\lib\\runpy.py\", line 87, in _run_code\n",
      "    exec(code, run_globals)\n",
      "  File \"C:\\Users\\rando\\anaconda3\\envs\\naparienv\\lib\\site-packages\\ipykernel_launcher.py\", line 16, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"C:\\Users\\rando\\anaconda3\\envs\\naparienv\\lib\\site-packages\\traitlets\\config\\application.py\", line 846, in launch_instance\n",
      "    app.start()\n",
      "  File \"C:\\Users\\rando\\anaconda3\\envs\\naparienv\\lib\\site-packages\\ipykernel\\kernelapp.py\", line 677, in start\n",
      "    self.io_loop.start()\n",
      "  File \"C:\\Users\\rando\\anaconda3\\envs\\naparienv\\lib\\site-packages\\tornado\\platform\\asyncio.py\", line 199, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"C:\\Users\\rando\\anaconda3\\envs\\naparienv\\lib\\asyncio\\base_events.py\", line 596, in run_forever\n",
      "    self._run_once()\n",
      "  File \"C:\\Users\\rando\\anaconda3\\envs\\naparienv\\lib\\asyncio\\base_events.py\", line 1890, in _run_once\n",
      "    handle._run()\n",
      "  File \"C:\\Users\\rando\\anaconda3\\envs\\naparienv\\lib\\asyncio\\events.py\", line 80, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Users\\rando\\anaconda3\\envs\\naparienv\\lib\\site-packages\\tornado\\ioloop.py\", line 741, in _run_callback\n",
      "    ret = callback()\n",
      "  File \"C:\\Users\\rando\\anaconda3\\envs\\naparienv\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 402, in advance_eventloop\n",
      "    eventloop(self)\n",
      "  File \"C:\\Users\\rando\\anaconda3\\envs\\naparienv\\lib\\site-packages\\ipykernel\\eventloops.py\", line 137, in loop_qt5\n",
      "    return loop_qt4(kernel)\n",
      "  File \"C:\\Users\\rando\\anaconda3\\envs\\naparienv\\lib\\site-packages\\ipykernel\\eventloops.py\", line 121, in loop_qt4\n",
      "    _loop_qt(kernel.app)\n",
      "  File \"C:\\Users\\rando\\anaconda3\\envs\\naparienv\\lib\\site-packages\\ipykernel\\eventloops.py\", line 105, in _loop_qt\n",
      "    app.exec_()\n",
      "  File \"C:\\Users\\rando\\anaconda3\\envs\\naparienv\\lib\\site-packages\\vispy\\app\\backends\\_qt.py\", line 567, in event\n",
      "    out = super(QtBaseCanvasBackend, self).event(ev)\n",
      "  File \"C:\\Users\\rando\\anaconda3\\envs\\naparienv\\lib\\site-packages\\vispy\\app\\backends\\_qt.py\", line 532, in mouseMoveEvent\n",
      "    self._vispy_mouse_move(\n",
      "  File \"C:\\Users\\rando\\anaconda3\\envs\\naparienv\\lib\\site-packages\\vispy\\app\\base.py\", line 216, in _vispy_mouse_move\n",
      "    ev = self._vispy_canvas.events.mouse_move(**kwargs)\n",
      "  File \"C:\\Users\\rando\\anaconda3\\envs\\naparienv\\lib\\site-packages\\vispy\\util\\event.py\", line 453, in __call__\n",
      "    self._invoke_callback(cb, event)\n",
      "  File \"C:\\Users\\rando\\anaconda3\\envs\\naparienv\\lib\\site-packages\\vispy\\util\\event.py\", line 469, in _invoke_callback\n",
      "    cb(event)\n",
      "  File \"C:\\Users\\rando\\AppData\\Roaming\\Python\\Python39\\site-packages\\napari\\_vispy\\canvas.py\", line 98, in _process_mouse_event\n",
      "    super()._process_mouse_event(event)\n",
      "  File \"C:\\Users\\rando\\anaconda3\\envs\\naparienv\\lib\\site-packages\\vispy\\scene\\canvas.py\", line 369, in _process_mouse_event\n",
      "    getattr(picked.events, event.type)(scene_event)\n",
      "  File \"C:\\Users\\rando\\anaconda3\\envs\\naparienv\\lib\\site-packages\\vispy\\util\\event.py\", line 453, in __call__\n",
      "    self._invoke_callback(cb, event)\n",
      "  File \"C:\\Users\\rando\\anaconda3\\envs\\naparienv\\lib\\site-packages\\vispy\\util\\event.py\", line 471, in _invoke_callback\n",
      "    _handle_exception(self.ignore_callback_errors,\n",
      "  << caught exception here: >>\n",
      "  File \"C:\\Users\\rando\\anaconda3\\envs\\naparienv\\lib\\site-packages\\vispy\\util\\event.py\", line 469, in _invoke_callback\n",
      "    cb(event)\n",
      "  File \"C:\\Users\\rando\\anaconda3\\envs\\naparienv\\lib\\site-packages\\vispy\\scene\\cameras\\perspective.py\", line 227, in viewbox_mouse_event\n",
      "    self._update_rotation(event)\n",
      "  File \"C:\\Users\\rando\\anaconda3\\envs\\naparienv\\lib\\site-packages\\vispy\\scene\\cameras\\arcball.py\", line 65, in _update_rotation\n",
      "    Quaternion(*_arcball(self._event_value, wh)) *\n",
      "  File \"C:\\Users\\rando\\anaconda3\\envs\\naparienv\\lib\\site-packages\\vispy\\scene\\cameras\\arcball.py\", line 101, in _arcball\n",
      "    x, y = xy\n",
      "ValueError: too many values to unpack (expected 2)\n",
      "WARNING:vispy:Traceback (most recent call last):\n",
      "  File \"C:\\Users\\rando\\anaconda3\\envs\\naparienv\\lib\\runpy.py\", line 197, in _run_module_as_main\n",
      "    return _run_code(code, main_globals, None,\n",
      "  File \"C:\\Users\\rando\\anaconda3\\envs\\naparienv\\lib\\runpy.py\", line 87, in _run_code\n",
      "    exec(code, run_globals)\n",
      "  File \"C:\\Users\\rando\\anaconda3\\envs\\naparienv\\lib\\site-packages\\ipykernel_launcher.py\", line 16, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"C:\\Users\\rando\\anaconda3\\envs\\naparienv\\lib\\site-packages\\traitlets\\config\\application.py\", line 846, in launch_instance\n",
      "    app.start()\n",
      "  File \"C:\\Users\\rando\\anaconda3\\envs\\naparienv\\lib\\site-packages\\ipykernel\\kernelapp.py\", line 677, in start\n",
      "    self.io_loop.start()\n",
      "  File \"C:\\Users\\rando\\anaconda3\\envs\\naparienv\\lib\\site-packages\\tornado\\platform\\asyncio.py\", line 199, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"C:\\Users\\rando\\anaconda3\\envs\\naparienv\\lib\\asyncio\\base_events.py\", line 596, in run_forever\n",
      "    self._run_once()\n",
      "  File \"C:\\Users\\rando\\anaconda3\\envs\\naparienv\\lib\\asyncio\\base_events.py\", line 1890, in _run_once\n",
      "    handle._run()\n",
      "  File \"C:\\Users\\rando\\anaconda3\\envs\\naparienv\\lib\\asyncio\\events.py\", line 80, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Users\\rando\\anaconda3\\envs\\naparienv\\lib\\site-packages\\tornado\\ioloop.py\", line 741, in _run_callback\n",
      "    ret = callback()\n",
      "  File \"C:\\Users\\rando\\anaconda3\\envs\\naparienv\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 402, in advance_eventloop\n",
      "    eventloop(self)\n",
      "  File \"C:\\Users\\rando\\anaconda3\\envs\\naparienv\\lib\\site-packages\\ipykernel\\eventloops.py\", line 137, in loop_qt5\n",
      "    return loop_qt4(kernel)\n",
      "  File \"C:\\Users\\rando\\anaconda3\\envs\\naparienv\\lib\\site-packages\\ipykernel\\eventloops.py\", line 121, in loop_qt4\n",
      "    _loop_qt(kernel.app)\n",
      "  File \"C:\\Users\\rando\\anaconda3\\envs\\naparienv\\lib\\site-packages\\ipykernel\\eventloops.py\", line 105, in _loop_qt\n",
      "    app.exec_()\n",
      "  File \"C:\\Users\\rando\\anaconda3\\envs\\naparienv\\lib\\site-packages\\vispy\\app\\backends\\_qt.py\", line 567, in event\n",
      "    out = super(QtBaseCanvasBackend, self).event(ev)\n",
      "  File \"C:\\Users\\rando\\anaconda3\\envs\\naparienv\\lib\\site-packages\\vispy\\app\\backends\\_qt.py\", line 532, in mouseMoveEvent\n",
      "    self._vispy_mouse_move(\n",
      "  File \"C:\\Users\\rando\\anaconda3\\envs\\naparienv\\lib\\site-packages\\vispy\\app\\base.py\", line 216, in _vispy_mouse_move\n",
      "    ev = self._vispy_canvas.events.mouse_move(**kwargs)\n",
      "  File \"C:\\Users\\rando\\anaconda3\\envs\\naparienv\\lib\\site-packages\\vispy\\util\\event.py\", line 453, in __call__\n",
      "    self._invoke_callback(cb, event)\n",
      "  File \"C:\\Users\\rando\\anaconda3\\envs\\naparienv\\lib\\site-packages\\vispy\\util\\event.py\", line 469, in _invoke_callback\n",
      "    cb(event)\n",
      "  File \"C:\\Users\\rando\\AppData\\Roaming\\Python\\Python39\\site-packages\\napari\\_vispy\\canvas.py\", line 98, in _process_mouse_event\n",
      "    super()._process_mouse_event(event)\n",
      "  File \"C:\\Users\\rando\\anaconda3\\envs\\naparienv\\lib\\site-packages\\vispy\\scene\\canvas.py\", line 369, in _process_mouse_event\n",
      "    getattr(picked.events, event.type)(scene_event)\n",
      "  File \"C:\\Users\\rando\\anaconda3\\envs\\naparienv\\lib\\site-packages\\vispy\\util\\event.py\", line 453, in __call__\n",
      "    self._invoke_callback(cb, event)\n",
      "  File \"C:\\Users\\rando\\anaconda3\\envs\\naparienv\\lib\\site-packages\\vispy\\util\\event.py\", line 471, in _invoke_callback\n",
      "    _handle_exception(self.ignore_callback_errors,\n",
      "  << caught exception here: >>\n",
      "  File \"C:\\Users\\rando\\anaconda3\\envs\\naparienv\\lib\\site-packages\\vispy\\util\\event.py\", line 469, in _invoke_callback\n",
      "    cb(event)\n",
      "  File \"C:\\Users\\rando\\anaconda3\\envs\\naparienv\\lib\\site-packages\\vispy\\scene\\cameras\\perspective.py\", line 227, in viewbox_mouse_event\n",
      "    self._update_rotation(event)\n",
      "  File \"C:\\Users\\rando\\anaconda3\\envs\\naparienv\\lib\\site-packages\\vispy\\scene\\cameras\\arcball.py\", line 65, in _update_rotation\n",
      "    Quaternion(*_arcball(self._event_value, wh)) *\n",
      "  File \"C:\\Users\\rando\\anaconda3\\envs\\naparienv\\lib\\site-packages\\vispy\\scene\\cameras\\arcball.py\", line 101, in _arcball\n",
      "    x, y = xy\n",
      "ValueError: too many values to unpack (expected 2)\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR: Invoking <bound method Base3DRotationCamera.viewbox_mouse_event of <ArcballCamera at 0x19eb8eec670>> for SceneMouseEvent\n",
      "ERROR:vispy:Invoking <bound method Base3DRotationCamera.viewbox_mouse_event of <ArcballCamera at 0x19eb8eec670>> for SceneMouseEvent\n",
      "C:\\Users\\rando\\AppData\\Roaming\\Python\\Python39\\site-packages\\napari\\_vispy\\layers\\image.py:242: UserWarning: data shape (22, 2292, 2292) exceeds GL_MAX_TEXTURE_SIZE 2048 in at least one axis and will be downsampled. Rendering is currently in 3D mode.\n",
      "  warnings.warn(\n"
     ]
    }
   ],
   "source": [
    "sourcedir = 'D:/TrainingData/Xenopus_oneat/raw'\n",
    "csv_dir = 'D:/TrainingData/Xenopus_oneat/csv/'\n",
    "Imageids = []\n",
    "Boxname = 'ImageIDBox'\n",
    "Path(csv_dir).mkdir(exist_ok = True)\n",
    "\n",
    "\n",
    "\n",
    "Raw_path = os.path.join(sourcedir, '*tif')\n",
    "X = glob.glob(Raw_path)\n",
    "for imagename in X:\n",
    "         Imageids.append(imagename)\n",
    "         Name = os.path.basename(os.path.splitext(imagename)[0])\n",
    "\n",
    "imageidbox = QComboBox()   \n",
    "imageidbox.addItem(Boxname)   \n",
    "tracksavebutton = QPushButton('Save Clicks')\n",
    "\n",
    "for i in range(0, len(Imageids)):\n",
    "\n",
    "\n",
    "     imageidbox.addItem(str(Imageids[i]))\n",
    "        \n",
    "        \n",
    "viewer = napari.Viewer()        \n",
    "viewer.window.add_dock_widget(imageidbox, name=\"Image\", area='bottom')    \n",
    "viewer.window.add_dock_widget(tracksavebutton, name=\"Save Clicks\", area='bottom')\n",
    "imageidbox.currentIndexChanged.connect(\n",
    "         lambda trackid = imageidbox: EventViewer(\n",
    "                 viewer,\n",
    "                  imageidbox.currentText(),\n",
    "                       os.path.basename(os.path.splitext(imageidbox.currentText())[0]), csv_dir, False, True ))     \n",
    "\n",
    "tracksavebutton.clicked.connect(\n",
    "        lambda trackid= tracksavebutton:EventViewer(\n",
    "                 viewer,\n",
    "                  imageidbox.currentText(),\n",
    "                       os.path.basename(os.path.splitext(imageidbox.currentText())[0]), csv_dir, True, False ))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "\n",
    "        "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python [conda env:naparienv] *",
   "language": "python",
   "name": "conda-env-naparienv-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.0"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
